resource/aws_rds_cluster: Support aurora-mysql and aurora-postgres Global Clusters (#12867)
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/12499
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/12524
Reference: https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-global-database.html
Reference: https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DBCluster.html (`EngineMode` note)

API support for Aurora MySQL 5.7 and PostgreSQL Global Clusters implemented their `EngineMode` as `provisioned` instead of the previous Aurora MySQL 5.6 `EngineMode` of `global`. The logic previously used this engine mode to guard the `DescribeGlobalCluster` and `RemoveFromGlobalCluster` API calls, however we will now need to call `DescribeGlobalCluster` for `provisioned` engine mode clusters to perform drift detection and properly handle deletion. We prefer this simple logic change at the expense of potential IAM permissions updates for operators versus complex version handling in the resource, which could be very bug prone over time.

Changes:

```
NOTES:

* resource/aws_rds_cluster: Due to recent API support for Aurora MySQL 5.7 and PostgreSQL Global Clusters which implemented the engine mode as `provisioned` instead of the previous `global` for Aurora MySQL 5.6, the resource now requires the `DescribeGlobalClusters` API call. Restrictive IAM permissions may require updates.

BUG FIXES:

* resource/aws_rds_cluster: Prevent unexpected `global_cluster_identifier` differences and deletion error with `aurora-mysql` and `aurora-postgresql` Global Cluster members
```

Previously in AWS Commerical before conditional update:

```
    TestAccAWSRDSCluster_GlobalClusterIdentifier_EngineMode_Provisioned: testing.go:669: Step 0 error: Check failed: Check 2/2 error: aws_rds_cluster.test: Attribute 'global_cluster_identifier' expected "tf-acc-test-3671312550212388967", got ""
    TestAccAWSRDSCluster_GlobalClusterIdentifier_EngineMode_Provisioned: testing.go:730: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.

        Error: errors during apply: error deleting RDS Cluster (tf-acc-test-3671312550212388967): InvalidDBClusterStateFault: This cluster is a part of a global cluster, please remove it from globalcluster first
```

Previously in AWS GovCloud (US) before error handling update:

```
    TestAccAWSRDSCluster_basic: testing.go:730: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.

        Error: errors during refresh: error reading RDS Global Cluster information for DB Cluster (tf-aurora-cluster-7839236307155079826): InvalidParameterValue: Access Denied to API Version: APIGlobalDatabases
```

Output from acceptance testing in AWS Commercial (test failure present on master and unrelated):

```
--- PASS: TestAccAWSRDSCluster_AvailabilityZones (125.61s)
--- PASS: TestAccAWSRDSCluster_BacktrackWindow (165.81s)
--- PASS: TestAccAWSRDSCluster_backupsUpdate (179.76s)
--- PASS: TestAccAWSRDSCluster_basic (141.21s)
--- PASS: TestAccAWSRDSCluster_ClusterIdentifierPrefix (123.01s)
--- PASS: TestAccAWSRDSCluster_copyTagsToSnapshot (225.08s)
--- PASS: TestAccAWSRDSCluster_DbSubnetGroupName (134.93s)
--- PASS: TestAccAWSRDSCluster_DeletionProtection (179.89s)
--- PASS: TestAccAWSRDSCluster_EnabledCloudwatchLogsExports (336.41s)
--- PASS: TestAccAWSRDSCluster_EnableHttpEndpoint (342.08s)
--- PASS: TestAccAWSRDSCluster_encrypted (138.67s)
--- PASS: TestAccAWSRDSCluster_EncryptedCrossRegionReplication (1680.90s)
--- PASS: TestAccAWSRDSCluster_EngineMode (430.89s)
--- PASS: TestAccAWSRDSCluster_EngineMode_Global (138.57s)
--- PASS: TestAccAWSRDSCluster_EngineMode_Multimaster (162.91s)
--- PASS: TestAccAWSRDSCluster_EngineMode_ParallelQuery (175.39s)
--- PASS: TestAccAWSRDSCluster_EngineVersion (156.68s)
--- PASS: TestAccAWSRDSCluster_EngineVersionWithPrimaryInstance (1094.60s)
--- PASS: TestAccAWSRDSCluster_generatedName (122.45s)
--- PASS: TestAccAWSRDSCluster_GlobalClusterIdentifier_EngineMode_Global (122.20s)
--- PASS: TestAccAWSRDSCluster_GlobalClusterIdentifier_EngineMode_Global_Add (133.04s)
--- PASS: TestAccAWSRDSCluster_GlobalClusterIdentifier_EngineMode_Global_Remove (150.16s)
--- PASS: TestAccAWSRDSCluster_GlobalClusterIdentifier_EngineMode_Global_Update (147.49s)
--- PASS: TestAccAWSRDSCluster_GlobalClusterIdentifier_EngineMode_Provisioned (140.56s)
--- PASS: TestAccAWSRDSCluster_iamAuth (176.97s)
--- PASS: TestAccAWSRDSCluster_kmsKey (177.05s)
--- PASS: TestAccAWSRDSCluster_missingUserNameCausesError (4.86s)
--- PASS: TestAccAWSRDSCluster_Port (263.90s)

--- FAIL: TestAccAWSRDSCluster_s3Restore (1510.33s)
    TestAccAWSRDSCluster_s3Restore: testing.go:669: Step 0 error: errors during apply:

        Error: Error waiting for RDS Cluster state to be "available": unexpected state 'migration-failed', wanted target 'available'. last error: %!s(<nil>)

--- PASS: TestAccAWSRDSCluster_ScalingConfiguration (353.62s)
--- PASS: TestAccAWSRDSCluster_SnapshotIdentifier (387.43s)
--- PASS: TestAccAWSRDSCluster_SnapshotIdentifier_DeletionProtection (426.21s)
--- PASS: TestAccAWSRDSCluster_SnapshotIdentifier_EncryptedRestore (375.94s)
--- PASS: TestAccAWSRDSCluster_SnapshotIdentifier_EngineMode_ParallelQuery (427.08s)
--- PASS: TestAccAWSRDSCluster_SnapshotIdentifier_EngineMode_Provisioned (389.84s)
--- PASS: TestAccAWSRDSCluster_SnapshotIdentifier_EngineVersion_Different (448.81s)
--- PASS: TestAccAWSRDSCluster_SnapshotIdentifier_EngineVersion_Equal (386.66s)
--- PASS: TestAccAWSRDSCluster_SnapshotIdentifier_MasterPassword (353.51s)
--- PASS: TestAccAWSRDSCluster_SnapshotIdentifier_MasterUsername (353.74s)
--- PASS: TestAccAWSRDSCluster_SnapshotIdentifier_PreferredBackupWindow (396.24s)
--- PASS: TestAccAWSRDSCluster_SnapshotIdentifier_PreferredMaintenanceWindow (376.32s)
--- PASS: TestAccAWSRDSCluster_SnapshotIdentifier_Tags (352.28s)
--- PASS: TestAccAWSRDSCluster_SnapshotIdentifier_VpcSecurityGroupIds (379.29s)
--- PASS: TestAccAWSRDSCluster_SnapshotIdentifier_VpcSecurityGroupIds_Tags (348.69s)
--- PASS: TestAccAWSRDSCluster_Tags (160.20s)
--- PASS: TestAccAWSRDSCluster_takeFinalSnapshot (164.84s)
--- PASS: TestAccAWSRDSCluster_updateIamRoles (169.77s)
```

Output from acceptance testing in AWS GovCloud (US) (this resource testing has not been fully updated to support this partition, but shows existing functionality working as before):

```
--- PASS: TestAccAWSRDSCluster_AvailabilityZones (129.68s)
--- PASS: TestAccAWSRDSCluster_backupsUpdate (215.28s)
--- PASS: TestAccAWSRDSCluster_basic (159.62s)
--- PASS: TestAccAWSRDSCluster_ClusterIdentifierPrefix (138.63s)
--- PASS: TestAccAWSRDSCluster_copyTagsToSnapshot (253.30s)
--- PASS: TestAccAWSRDSCluster_DbSubnetGroupName (172.06s)
--- PASS: TestAccAWSRDSCluster_DeletionProtection (215.43s)
--- PASS: TestAccAWSRDSCluster_encrypted (171.10s)
--- PASS: TestAccAWSRDSCluster_iamAuth (169.61s)
--- PASS: TestAccAWSRDSCluster_kmsKey (175.66s)
--- PASS: TestAccAWSRDSCluster_SnapshotIdentifier (453.06s)
--- PASS: TestAccAWSRDSCluster_SnapshotIdentifier_DeletionProtection (515.03s)
--- PASS: TestAccAWSRDSCluster_SnapshotIdentifier_EncryptedRestore (401.20s)
--- PASS: TestAccAWSRDSCluster_SnapshotIdentifier_EngineMode_Provisioned (400.98s)
--- PASS: TestAccAWSRDSCluster_SnapshotIdentifier_MasterPassword (432.35s)
--- PASS: TestAccAWSRDSCluster_SnapshotIdentifier_MasterUsername (443.88s)
--- PASS: TestAccAWSRDSCluster_SnapshotIdentifier_PreferredMaintenanceWindow (400.99s)
--- PASS: TestAccAWSRDSCluster_SnapshotIdentifier_Tags (444.46s)
--- PASS: TestAccAWSRDSCluster_SnapshotIdentifier_VpcSecurityGroupIds (498.80s)
--- PASS: TestAccAWSRDSCluster_SnapshotIdentifier_VpcSecurityGroupIds_Tags (456.84s)
--- PASS: TestAccAWSRDSCluster_Tags (159.57s)
--- PASS: TestAccAWSRDSCluster_takeFinalSnapshot (222.58s)
--- PASS: TestAccAWSRDSCluster_updateIamRoles (173.80s)
```